server:
  port: 8084
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/reviewAndCommentService
      database: reviewAndCommentService
  application:
    name: REVIEW-SERVICE
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instanceId: ${spring.application.name}
    hostname: localhost

okta:
  oauth2:
    issuer: https://dev-40949592.okta.com/oauth2/default
    audience: api://default