server:
  port: '8084'
management:
  endpoints:
    web:
      exposure:
        include: "*"
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/inventoryService
      database: inventoryService

  application:
    name: INVENTORY-SERVICE
springdoc:
  swagger-ui:
    path: "/inventory-api-docs.html"
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/