logging:
  level:
    org:
      apache:
        kafka: OFF

server:
  port: '8084'
management:
  endpoints:
    web:
      exposure:
        include: "*"
spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: Inventory-Service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

  data:
    mongodb:
      uri: mongodb://localhost:27017/inventoryService
      database: inventoryService

  application:
    name: INVENTORY-SERVICE
springdoc:
  swagger-ui:
    path: "/inventory-api-docs.html"
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/