server:
  port: '8082'
  error:
    include-message: always
spring:

  kafka:
    bootstrap-servers: localhost:9002
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

  datasource:
    password: Suryansh@1904
    url: jdbc:postgresql://localhost:5432/E-Store
    username: postgres
    hikari:
      schema: Order-Service

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  main:
    allow-bean-definition-overriding: true
  application:
    name: ORDER-SERVICE

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instanceId: ${spring.application.name}
    hostname: localhost